name: iot_internal
description: Common codecs and crypto feature for iot websocket server and client.
version: 1.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <3.5.0'

dependencies:
  #Architecture
  bloc: ^8.1.2

  #Tools
  encrypt: ^5.0.1

  iot_models:
    git:
      url: https://github.com/NikitaMasev/iot_models.git
      ref: main

dev_dependencies:
  lints: ^2.1.1
