name: iot_internal
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  #Architecture
  bloc: ^8.1.0

  #Tools
  encrypt: ^5.0.1

  iot_models:
    git:
      url: https://github.com/NikitaMasev/iot_models.git
      ref: main

dev_dependencies:
  lints: ^2.0.0
